### ISSUE TITLE
Stylelint v7

### ISSUE THREAD

**Issue by ajhyndman** [shinnn/stylelint-vscode#1]
Thanks very much for putting this together!  Stylelint recently released version 7.0.0.  Would you consider pull requests updating that dependency here?

**Comment by shinnn** [comment]
Fixed in https://github.com/shinnn/stylelint-vscode/commit/43762fe5c34a9c107380fa49a4f040ee894283f9.

**Comment by ajhyndman** [comment]
Awesome, thanks.  :+1:
