### ISSUE TITLE
Why you don't use VS Code API for search of package?

### ISSUE THREAD

**Issue by mrmlnc** [shinnn/stylelint-vscode#2]
VS Code API (language-server) provides a useful API for searching local or global package.

> But it's a must do during initialization, so as not to look for a module every time.

For example:

```js
const { Files } = require('vscode-languageserver');

connection.onInitialize((params) => {
  workspaceDir = params.rootPath;
  return Files.resolveModule(workspaceDir, 'pug-lint')
    .then((Linter) => {
      linter = new Linter();

      return {
        capabilities: {
          textDocumentSync: documents.syncKind
        }
      };
    })
    .catch(() => {
      const res = {
        code: 99,
        message: 'Failed to load pug-lint library. Please install pug-lint in your workspace folder using \'npm install pug-lint\' or globally using \'npm install -g pug-lint\' and then press Retry.',
        options: {
          retry: true
        }
      };

      return Promise.reject(new ResponseError(res.code, res.message, res.options));
    });
});
```

It seems to me that keep Linter in the package - it's a bad idea. For example, in my extensions Linter is installed separately:

  * https://github.com/mrmlnc/vscode-puglint (with File method: https://github.com/mrmlnc/vscode-puglint/blob/068bf071c80e8e36dcb11c43d29bfdd326561a05/server.js#L227-L250)
  * https://github.com/mrmlnc/vscode-autoprefixer
  * https://github.com/mrmlnc/vscode-doiuse

If you don't want to use the built-in API, you can use my package :sweat_smile:.

  * https://github.com/mrmlnc/npm-module-path

**Comment by shinnn** [comment]
> It seems to me that keep Linter in the package - it's a bad idea

Depending on user-installed packages is even worse idea.

**Comment by kumarharsh** [comment]
@shinnn can you expand on why you think it is a bad idea? Not being hostile, just want to know your views. Because now vscode's eslint plugin also can depend on the user-installed package. And it is very helpful, as a user can have different settings per project.

**Comment by shinnn** [comment]
I have a definite answer for this question and will comment it on https://github.com/shinnn/vscode-stylelint/issues/4 when I have time.

@mrmlnc Sorry, https://github.com/shinnn/stylelint-vscode/issues/2#issuecomment-236482684 was a bit offensive.

**Comment by kumarharsh** [comment]
@shinnn why did you delete all the discussion in the other issue? We were just offering suggestions here.

**Comment by shinnn** [comment]
@kumarharsh I do just what I want to do. The project owner is me.

**Comment by williscool** [comment]
@shinnn you could avoid a lot of being bothered and having your time wasted with the exact same issue and derivatives of #8 if you would just comment why you think its a bad idea to have an option to override with the project folder's stylelint.
