### ISSUE TITLE
Upgrade stylelint to 7.8.0

### ISSUE THREAD

**Issue by onedesert** [shinnn/stylelint-vscode#5]
Can we upgrade version of stylelint to be hable to use new rules.

**Comment by shinnn** [comment]
https://github.com/shinnn/stylelint-vscode/search?q=7.8.0&type=Issues&utf8=%E2%9C%93

**Comment by onedesert** [comment]
Just to let you know that force me to reinstall the vscode extension each time, but now that I know it's ok.

**Comment by shinnn** [comment]
> that force me to reinstall the vscode extension each time

No.
