### ISSUE TITLE
Upgrade stylelint to 8.0.0

### ISSUE THREAD

**Issue by timbru31** [shinnn/stylelint-vscode#7]
Stylelint v8.0.0 is out, so this package needs to be updated 🎉  
Changelog: https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#800

**Comment by timbru31** [comment]
Awesome, thanks! In case you don't know the service yet, https://greenkeeper.io/ is a great help to have automatic PRs with updated dependencies! 👍

**Comment by shinnn** [comment]
I know, but it's too noisy and messy.
