### ISSUE TITLE
Upgrade to stylelint 8.3.0

### ISSUE THREAD

**Issue by chrisvfritz** [shinnn/stylelint-vscode#9]
Would it be possible to upgrade the bundled version of stylelint to [the just-released 8.3.0](https://github.com/stylelint/stylelint/releases/tag/8.3.0)? It includes important support for the Vue community. 🙂

**Comment by shinnn** [comment]
Sure. Also I'm planning to add more HTML(-like) syntaxes to the [default `documentSelector`](https://github.com/shinnn/vscode-stylelint/blob/254cfadf345cde48f5ae55ebf078a15a51eb86da/index.js#L26):

* `html`
* `xml`
* `svg`
* `markdown`
* `vue`
* `vue-html`

Do you know anything else vscode-stylelint should support by default?

**Comment by chrisvfritz** [comment]
That list covers everything I can think of.
